on:
  issues:
    types: [assigned]
jobs:
  Move_Labeled_Issue_On_Project_Board:
    runs-on: ubuntu-latest
    steps:
    - uses: konradpabjan/move-labeled-or-milestoned-issue@v2.0
      with:
        action-token: "${{ secrets.DOCS_API_KEY }}"
        project-url: "https://github.com/users/PriyankaVasant/projects/8"
        label-name: "issues"
        column-name: "In Progress"
